AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lighthouse Keeper

Parameters:
  SpreadSheetID:
    Type: String
  GCloudProject:
    Type: String
  SSMNameForClientEmail:
    Type: String
  SSMNameForClientKey:
    Type: String
  SQSQueueURL:
    Type: String
  S3BucketName:
    Type: String

Resources:
  LighthouseKeeperProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: ./functions/producer
      Handler: dist/index.handler
      Runtime: nodejs12.x
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt LighthouseKeeperSqsQueue.QueueName
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SQSQueueURL

  LighthouseKeeperConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: ./functions/consumer
      Handler: dist/index.handler
      Runtime: nodejs12.x
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt LighthouseKeeperIntegrationStateMachine.Name
      Events:
        LighthouseKeeperSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt LighthouseKeeperSqsQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          STATE_MACHINE: !Ref LighthouseKeeperIntegrationStateMachine
  
  LighthouseKeeperRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      Timeout: 300
      CodeUri: ./functions/runner
      Handler: dist/index.handler
      Runtime: nodejs12.x

  LighthouseKeeperSpreadSheetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      CodeUri: ./functions/integration/spread_sheets
      Handler: dist/index.handler
      Runtime: nodejs12.x
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          SPREAD_SHEET_ID: !Ref SpreadSheetID
          GCLOUD_PROJECT: !Ref GCloudProject
          SSM_NAME_FOR_CLIENT_EMAIL: !Ref SSMNameForClientEmail
          SSM_NAME_FOR_CLIENT_KEY: !Ref SSMNameForClientKey

  LighthouseKeeperS3Function:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: ./functions/integration/s3
      Handler: dist/index.handler
      Runtime: nodejs12.x
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  LighthouseKeeperIntegrationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step_functions/integration.asl.json
      DefinitionSubstitutions:
        LighthouseKeeperRunnerFunctionArn: !GetAtt LighthouseKeeperRunnerFunction.Arn
        LighthouseKeeperSpreadSheetsFunctionArn: !GetAtt LighthouseKeeperSpreadSheetsFunction.Arn
        LighthouseKeeperS3FunctionArn: !GetAtt LighthouseKeeperS3Function.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LighthouseKeeperSpreadSheetsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref LighthouseKeeperRunnerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref LighthouseKeeperS3Function

  LighthouseKeeperSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 600
