AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lighthouse Keeper

Parameters:
  SpreadSheetID:
    Type: String
  GCloudProject:
    Type: String
  SSMNameForClientEmail:
    Type: String
  SSMNameForClientKey:
    Type: String
  SQSQueueURL:
    Type: String

Globals:
  Function:
    Timeout: 300

Resources:
  LighthouseKeeperProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: ./functions/producer
      Handler: dist/index.handler
      Runtime: nodejs12.x
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt LighthouseKeeperSqsQueue.QueueName
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SQSQueueURL

  LighthouseKeeperConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      CodeUri: ./functions/consumer
      Handler: dist/index.handler
      Runtime: nodejs12.x
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Events:
        LighthouseKeeperSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt LighthouseKeeperSqsQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          SPREAD_SHEET_ID: !Ref SpreadSheetID
          GCLOUD_PROJECT: !Ref GCloudProject
          SSM_NAME_FOR_CLIENT_EMAIL: !Ref SSMNameForClientEmail
          SSM_NAME_FOR_CLIENT_KEY: !Ref SSMNameForClientKey

  LighthouseKeeperSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 600

Outputs:
  LighthouseKeeperConsumerFunction:
    Description: "Worker Lambda Function ARN"
    Value: !GetAtt LighthouseKeeperConsumerFunction.Arn
  LighthouseKeeperConsumerFunctionIamRole:
    Description: "Implicit IAM Role created for Worker function"
    Value: !GetAtt LighthouseKeeperConsumerFunctionRole.Arn
